version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=development
    ports:
      - "8081:8080"

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=production
    ports:
      - "8082:8080"
